from __future__ import annotations

from typing import Any, Dict, List

import pytest

from dwpy.runtime import DataWeaveRuntime


CASE_MATRIX: List[Dict[str, Any]] = [
    {
        "id": "extract_data",
        "title": "Extract Data",
        "source_adoc": "dataweave-cookbook-extract-data.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{id: payload.user.id, city: payload.user.address.city}\n",
        "payload": {"user": {"id": "u1", "address": {"city": "BA"}}},
        "expected": {"id": "u1", "city": "BA"},
    },
    {
        "id": "select_xml_elements",
        "title": "Select XML Elements",
        "source_adoc": "dataweave-cookbook-select-xml-elements.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{title: payload.catalog.book.title}\n",
        "payload": "<catalog><book><title>DW</title></book></catalog>",
        "payload_format": "application/xml",
        "expected": {"title": "DW"},
    },
    {
        "id": "set_default_value",
        "title": "Set a Default Value",
        "source_adoc": "dataweave-cookbook-defaults.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{id: payload.id default \"000\", name: payload.name default \"Undefined\"}\n",
        "payload": {"id": None},
        "expected": {"id": "000", "name": "Undefined"},
    },
    {
        "id": "set_reader_writer_config_properties",
        "title": "Set Reader and Writer Configuration Properties",
        "source_adoc": "dataweave-cookbook-set-reader-writer-props.adoc",
        "script": "%dw 2.0\noutput application/csv separator=\";\" header=true\n---\npayload\n",
        "payload": [{"name": "Ann", "age": 20}],
        "render_output": True,
        "expected": "name;age\nAnn;20\n",
    },
    {
        "id": "transform_xml_to_json",
        "title": "Transform XML to JSON",
        "source_adoc": "dataweave-cookbook-perform-basic-transformation.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{name: payload.order.customer.name, total: payload.order.total}\n",
        "payload": "<order><customer><name>Ada</name></customer><total>10</total></order>",
        "payload_format": "application/xml",
        "expected": {"name": "Ada", "total": "10"},
    },
    {
        "id": "map_data",
        "title": "Map Data",
        "source_adoc": "dataweave-cookbook-map.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{items: payload.books map {title: $.title, price: $.price as Number, id: $$}}\n",
        "payload": {"books": [{"title": "A", "price": "1.50"}]},
        "expected": {"items": [{"title": "A", "price": 1.5, "id": 0}]},
    },
    {
        "id": "map_and_flatten_array",
        "title": "Map and Flatten an Array",
        "source_adoc": "dataweave-cookbook-map-and-flatten.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload flatMap ((item) -> item.tags map ((tag) -> {id: item.id, tag: tag}))\n",
        "payload": [{"id": 1, "tags": ["a", "b"]}],
        "expected": [{"id": 1, "tag": "a"}, {"id": 1, "tag": "b"}],
    },
    {
        "id": "map_objects",
        "title": "Map Objects",
        "source_adoc": "dataweave-cookbook-map-an-object.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n(entriesOf(payload) map ((entry) -> {(upper(entry.key)): entry.value})) reduce ((item, acc={}) -> acc ++ item)\n",
        "payload": {"name": "Max", "city": "BA"},
        "expected": {"NAME": "Max", "CITY": "BA"},
    },
    {
        "id": "map_objects_key",
        "title": "Map Objects Key",
        "source_adoc": "dataweave-cookbook-map-an-object-key.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload map ((item) -> item ++ {matched: item.name == vars.target})\n",
        "payload": [{"name": "Alice"}, {"name": "Bob"}],
        "vars": {"target": "Bob"},
        "expected": [{"name": "Alice", "matched": False}, {"name": "Bob", "matched": True}],
    },
    {
        "id": "map_objects_within_array",
        "title": "Map the Objects within an Array",
        "source_adoc": "dataweave-cookbook-map-object-elements-as-an-array.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload.catalog.*book map ((book) -> {title: book.title})\n",
        "payload": {"catalog": {"book": [{"title": "A"}, {"title": "B"}]}},
        "expected": [{"title": "A"}, {"title": "B"}],
    },
    {
        "id": "dynamic_map_based_on_definition",
        "title": "Dynamic Map Based on a Definition",
        "source_adoc": "dataweave-cookbook-map-based-on-an-external-definition.adoc",
        "script": "%dw 2.0\noutput application/json\nvar defs = vars.defs\nfun pick(input,key)= input[key] default null\n---\ndefs map ((d) -> {(d.to): pick(payload,d.from)})\n",
        "payload": {"first_name": "Max", "age": 20},
        "vars": {"defs": [{"from": "first_name", "to": "firstName"}, {"from": "age", "to": "age"}]},
        "expected": [{"firstName": "Max"}, {"age": 20}],
    },
    {
        "id": "rename_keys",
        "title": "Rename Keys",
        "source_adoc": "dataweave-cookbook-rename-keys.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{firstName: payload.name} ++ (payload -- {name: payload.name})\n",
        "payload": {"name": "Max", "city": "BA"},
        "expected": {"firstName": "Max", "city": "BA"},
    },
    {
        "id": "output_field_when_present",
        "title": "Output a Field When Present",
        "source_adoc": "dataweave-cookbook-output-a-field-when-present.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload.users map ((u) -> if (u.email != null) {name:u.name, email:u.email} else {name:u.name})\n",
        "payload": {"users": [{"name": "A", "email": "a@x"}, {"name": "B"}]},
        "expected": [{"name": "A", "email": "a@x"}, {"name": "B"}],
    },
    {
        "id": "format_according_to_type",
        "title": "Format According to Type",
        "source_adoc": "dataweave-cookbook-format-according-to-type.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n(entriesOf(payload) map ((entry) -> if ((entry.value as String) matches \"/^[0-9]+$/\") {(entry.key): (entry.value as Number) * 10} else {(entry.key): upper(entry.value)})) reduce ((item, acc={}) -> acc ++ item)\n",
        "payload": {"name": "ada", "count": 3},
        "expected": {"name": "ADA", "count": 30},
    },
    {
        "id": "regroup_fields",
        "title": "Regroup Fields",
        "source_adoc": "dataweave-cookbook-regroup-fields.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload groupBy ((item) -> item.department)\n",
        "payload": [{"department": "ENG", "name": "A"}, {"department": "ENG", "name": "B"}, {"department": "OPS", "name": "C"}],
        "expected": {
            "ENG": [{"department": "ENG", "name": "A"}, {"department": "ENG", "name": "B"}],
            "OPS": [{"department": "OPS", "name": "C"}],
        },
    },
    {
        "id": "zip_arrays_together",
        "title": "Zip Arrays Together",
        "source_adoc": "dataweave-cookbook-zip-arrays-together.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload.a map ((value, index) -> [value, payload.b[index]])\n",
        "payload": {"a": [1, 2], "b": ["x", "y"]},
        "expected": [[1, "x"], [2, "y"]],
    },
    {
        "id": "pick_top_elements",
        "title": "Pick Top Elements",
        "source_adoc": "dataweave-cookbook-pick-top-elements.adoc",
        "script": "%dw 2.0\noutput application/json\nvar grouped = payload groupBy ((candidate) -> candidate.test)\n---\n(entriesOf(grouped) map ((entry) -> {(entry.key): maxBy(entry.value, (c) -> c.score)})) reduce ((item, acc={}) -> acc ++ item)\n",
        "payload": [{"name": "A", "test": "math", "score": 70}, {"name": "B", "test": "math", "score": 95}, {"name": "C", "test": "english", "score": 80}],
        "expected": {
            "math": {"name": "B", "test": "math", "score": 95},
            "english": {"name": "C", "test": "english", "score": 80},
        },
    },
    {
        "id": "change_value_of_field",
        "title": "Change the Value of a Field",
        "source_adoc": "dataweave-cookbook-change-value-of-a-field.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload map ((user) -> user ++ {password: if (user.password != null) \"****\" else null})\n",
        "payload": [{"name": "A", "password": "1234"}],
        "expected": [{"name": "A", "password": "****"}],
    },
    {
        "id": "exclude_fields_output",
        "title": "Exclude Fields from the Output",
        "source_adoc": "dataweave-cookbook-exclude-field.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload map ((item) -> item -- {ssn: item.ssn})\n",
        "payload": [{"name": "A", "ssn": "111"}],
        "expected": [{"name": "A"}],
    },
    {
        "id": "use_constant_directives",
        "title": "Use Constant Directives",
        "source_adoc": "dataweave-cookbook-use-constant-directives.adoc",
        "script": "%dw 2.0\noutput application/json\nvar base = \"https://api.example.com/\"\nvar active = \"active\"\n---\n(payload.users filter ((u) -> u.status == active)) map ((u) -> {url: base ++ u.id})\n",
        "payload": {"users": [{"id": "1", "status": "active"}, {"id": "2", "status": "inactive"}]},
        "expected": [{"url": "https://api.example.com/1"}],
    },
    {
        "id": "define_custom_addition_function",
        "title": "Define a Custom Addition Function",
        "source_adoc": "dataweave-cookbook-define-a-custom-addition-function.adoc",
        "script": "%dw 2.0\noutput application/json\nfun lineTotal(item) = item.qty * item.price\n---\n{total: sum(payload.items map ((item) -> lineTotal(item)))}\n",
        "payload": {"items": [{"qty": 2, "price": 10}, {"qty": 1, "price": 5}]},
        "expected": {"total": 25},
    },
    {
        "id": "define_function_flattens_list",
        "title": "Define a Function That Flattens Data in a List",
        "source_adoc": "dataweave-cookbook-define-function-to-flatten-list.adoc",
        "script": "%dw 2.0\noutput application/json\nfun collect(items)= items reduce ((item, acc=[]) -> acc ++ (item.tags splitBy \",\"))\n---\ncollect(payload.items)\n",
        "payload": {"items": [{"tags": "a,b"}, {"tags": "c,d"}]},
        "expected": ["a", "b", "c", "d"],
    },
    {
        "id": "flatten_elements_arrays",
        "title": "Flatten Elements of Arrays",
        "source_adoc": "dataweave-cookbook-flatten-arrays.adoc",
        "script": "%dw 2.0\noutput application/json\n---\nflatten(payload.left ++ payload.right)\n",
        "payload": {"left": [[1], [2]], "right": [[3]]},
        "expected": [1, 2, 3],
    },
    {
        "id": "use_regular_expressions",
        "title": "Use Regular Expressions",
        "source_adoc": "dataweave-cookbook-use-regex.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{indices: payload.text find \"foo\", starts: payload.text startsWith \"xx\"}\n",
        "payload": {"text": "xxfooxfoo"},
        "expected": {"indices": [2, 6], "starts": True},
    },
    {
        "id": "output_self_closing_xml_tags",
        "title": "Output Self-closing XML Tags",
        "source_adoc": "dataweave-cookbook-output-self-closing-xml-tags.adoc",
        "script": "%dw 2.0\noutput application/xml inlineCloseOn=\"empty\"\n---\n{root: {element1: \"text\", element2: null}}\n",
        "payload": {},
        "render_output": True,
        "expected_contains": ["<element2 />"],
    },
    {
        "id": "insert_attribute_xml_tag",
        "title": "Insert an Attribute into an XML Tag",
        "source_adoc": "dataweave-cookbook-insert-attribute.adoc",
        "script": "%dw 2.0\noutput application/xml\n---\n{user: {\"@id\": \"123\", \"#text\": \"Max\"}}\n",
        "payload": {},
        "render_output": True,
        "expected_contains": ["<user id=\"123\">Max</user>"],
    },
    {
        "id": "remove_specified_xml_attributes",
        "title": "Remove Specified XML Attributes",
        "source_adoc": "dataweave-cookbook-remove-certain-xml-attributes.adoc",
        "script": "%dw 2.0\noutput application/xml\n---\n{customer: (payload.root.customer -- {\"@secret\": payload.root.customer[\"@secret\"]})}\n",
        "payload": "<root><customer id=\"7\" secret=\"x\">Ada</customer></root>",
        "payload_format": "application/xml",
        "render_output": True,
        "expected_contains": ["<customer id=\"7\">Ada</customer>"],
    },
    {
        "id": "pass_xml_attributes",
        "title": "Pass XML Attributes",
        "source_adoc": "dataweave-cookbook-pass-xml-attributes.adoc",
        "script": "%dw 2.0\noutput application/xml\n---\n{customer: {\"@id\": payload.root.customer[\"@id\"], \"#text\": payload.root.customer[\"#text\"]}}\n",
        "payload": "<root><customer id=\"7\">Ada</customer></root>",
        "payload_format": "application/xml",
        "render_output": True,
        "expected_contains": ["<customer id=\"7\">Ada</customer>"],
    },
    {
        "id": "include_xml_namespaces",
        "title": "Include XML Namespaces",
        "source_adoc": "dataweave-cookbook-include-xml-namespaces.adoc",
        "script": "%dw 2.0\noutput application/xml\n---\n{root: {\"@xmlns:h\": \"http://www.w3.org/TR/html4/\", \"h:table\": {\"h:tr\": {\"h:td\": \"Apples\"}}}}\n",
        "payload": {},
        "render_output": True,
        "expected_contains": ["xmlns:h=\"http://www.w3.org/TR/html4/\"", "<h:td>Apples</h:td>"],
    },
    {
        "id": "remove_objects_by_key_value",
        "title": "Remove Objects Containing Specified Key-Value Pairs",
        "source_adoc": "dataweave-cookbook-remove-objects.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload filter ((item) -> ((item.country == \"US\") and (item.status == \"inactive\")) == false)\n",
        "payload": [{"country": "US", "status": "inactive"}, {"country": "US", "status": "active"}],
        "expected": [{"country": "US", "status": "active"}],
    },
    {
        "id": "reference_multiple_inputs",
        "title": "Reference Multiple Inputs",
        "source_adoc": "dataweave-cookbook-reference-multiple-inputs.adoc",
        "script": "%dw 2.0\noutput application/json\n---\n{scaled: payload.values map ((v) -> v * vars.multiplier), filtered: payload.values filter ((v) -> v > vars.min)}\n",
        "payload": {"values": [1, 2, 3]},
        "vars": {"multiplier": 10, "min": 1},
        "expected": {"scaled": [10, 20, 30], "filtered": [2, 3]},
    },
    {
        "id": "merge_fields_from_separate_objects",
        "title": "Merge Fields from Separate Objects",
        "source_adoc": "dataweave-cookbook-merge-multiple-payloads.adoc",
        "script": "%dw 2.0\noutput application/json\n---\npayload.orders map ((o) -> o ++ ((vars.customers filter ((c) -> c.id == o.customerId))[0] default {}))\n",
        "payload": {"orders": [{"orderId": 1, "customerId": "c1"}]},
        "vars": {"customers": [{"id": "c1", "name": "Acme"}]},
        "expected": [{"orderId": 1, "customerId": "c1", "id": "c1", "name": "Acme"}],
    },
    {
        "id": "parse_dates",
        "title": "Parse Dates",
        "source_adoc": "dataweave-cookbook-parse-dates.adoc",
        "script": "%dw 2.0\noutput application/json\nfun normalize(value) = if (value contains \".\") ((value splitBy \".\")[2] ++ \"-\" ++ (value splitBy \".\")[1] ++ \"-\" ++ (value splitBy \".\")[0]) else value\n---\npayload map ((item) -> item ++ {normalized: normalize(item.date)})\n",
        "payload": [{"date": "2024-01-31"}, {"date": "31.01.2024"}],
        "expected": [{"date": "2024-01-31", "normalized": "2024-01-31"}, {"date": "31.01.2024", "normalized": "2024-01-31"}],
    },
    {
        "id": "add_subtract_dates",
        "title": "Add and Subtract Dates",
        "source_adoc": "dataweave-cookbook-add-and-subtract-time.adoc",
        "script": "%dw 2.0\noutput application/json\nvar dateParts = payload.date splitBy \"-\"\nvar year = dateParts[0]\nvar month = dateParts[1]\nvar day = dateParts[2] as Number\n---\n{added: year ++ \"-\" ++ month ++ \"-\" ++ ((day + payload.addDays) as String), subtracted: year ++ \"-\" ++ month ++ \"-\" ++ ((day + payload.subDays) as String)}\n",
        "payload": {"date": "2024-01-10", "addDays": 2, "subDays": -3},
        "expected": {"added": "2024-01-12", "subtracted": "2024-01-7"},
    },
    {
        "id": "change_time_zone",
        "title": "Change a Time Zone",
        "source_adoc": "dataweave-cookbook-change-time-zone.adoc",
        "script": "%dw 2.0\noutput application/json\nvar date = (payload.timestamp splitBy \"T\")[0]\nvar time = (payload.timestamp splitBy \"T\")[1]\nvar hour = (time splitBy \":\")[0] as Number\nvar tail = (time splitBy \":\")[1] ++ \":\" ++ (time splitBy \":\")[2]\n---\n{timezone: payload.targetTimeZone, converted: date ++ \"T\" ++ ((hour + payload.shiftHours) as String) ++ \":\" ++ tail ++ payload.targetOffset}\n",
        "payload": {"timestamp": "2024-01-10T10:30:00", "shiftHours": 2, "targetTimeZone": "Europe/Berlin", "targetOffset": "+02:00"},
        "expected": {"timezone": "Europe/Berlin", "converted": "2024-01-10T12:30:00+02:00"},
    },
    {
        "id": "format_dates_times",
        "title": "Format Dates and Times",
        "source_adoc": "dataweave-cookbook-format-dates.adoc",
        "script": "%dw 2.0\noutput application/json\nvar dateParts = (payload.ts splitBy \"T\")[0] splitBy \"-\"\nvar timeParts = (payload.ts splitBy \"T\")[1] splitBy \":\"\n---\n{formatted: dateParts[2] ++ \"/\" ++ dateParts[1] ++ \"/\" ++ dateParts[0] ++ \" \" ++ timeParts[0] ++ \":\" ++ timeParts[1]}\n",
        "payload": {"ts": "2024-01-31T10:20:30"},
        "expected": {"formatted": "31/01/2024 10:20"},
    },
    {
        "id": "work_with_multipart_data",
        "title": "Work with Multipart Data",
        "source_adoc": "dataweave-cookbook-work-with-multipart-data.adoc",
        "script": "%dw 2.0\noutput application/json\nvar boundary = vars.boundary\n---\n((payload splitBy (\"--\" ++ boundary)) filter ((part) -> part contains \"name=\")) map ((part) -> trim(part))\n",
        "payload": "--b\nContent-Disposition: form-data; name=\"field1\"\n\nvalue1\n--b--",
        "vars": {"boundary": "b"},
        "expected": ["Content-Disposition: form-data; name=\"field1\"\n\nvalue1"],
    },
    {
        "id": "conditional_reduce_list_via_function",
        "title": "Conditionally Reduce a List through a Function",
        "source_adoc": "dataweave-cookbook-conditional-list-reduction-via-function.adoc",
        "script": "%dw 2.0\noutput application/json\nfun collect(items)= items reduce ((item, acc=[]) -> acc ++ (item.tags splitBy \",\"))\n---\npayload.users map ((u) -> {name:u.name, tags: if (u.tags != null) collect([u]) else []})\n",
        "payload": {"users": [{"name": "A", "tags": "x,y"}, {"name": "B"}]},
        "expected": [{"name": "A", "tags": ["x", "y"]}, {"name": "B", "tags": []}],
    },
    {
        "id": "pass_functions_as_arguments",
        "title": "Pass Functions as Arguments",
        "source_adoc": "dataweave-cookbook-pass-functions-as-arguments.adoc",
        "script": "%dw 2.0\noutput application/json\nfun applyEach(f, arr) = arr map ((item) -> f(item))\nfun up(s)= upper(s)\n---\napplyEach(up, payload.names)\n",
        "payload": {"names": ["a", "b"]},
        "expected": ["A", "B"],
    },
]


@pytest.mark.parametrize("case", CASE_MATRIX, ids=[case["id"] for case in CASE_MATRIX])
def test_cookbook_code_examples(case: Dict[str, Any]) -> None:
    runtime = DataWeaveRuntime()
    render_output = bool(case.get("render_output", False))

    result = runtime.execute(
        case["script"],
        payload=case.get("payload", {}),
        vars=case.get("vars"),
        payload_format=case.get("payload_format"),
        payload_format_options=case.get("payload_format_options"),
        render_output=render_output,
    )

    expected = case.get("expected")
    if expected is not None:
        assert result == expected

    for snippet in case.get("expected_contains", []):
        assert isinstance(result, str)
        assert snippet in result
